version: "3"

services:
  backend-services:
    build:
      context: ./backend
      dockerfile: backend-service.dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./.env:/.env
    deploy:
      mode: replicated
      replicas: 1

  frontend-service:
    build:
      context: ./frontend
      dockerfile: frontend-service.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
